name: main
on:
  # push:
  #   branches:
  #     - main
  schedule:
    # Runs daily
    - cron:  '0 0 * * *'

jobs:
  build:
    name: Pokemon Github Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json

        # Same as npm install but installs all exact version deps
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Targets the current working directory, and will find action.yml
      - name: Run action.yml
        uses: ./
        with:
          name: 'Get most popular pokemon'
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "paulwongx"
          git config user.email "20178251+paulwongx@users.noreply.github.com"
          npm run git "latest"